[Project]
cubic_version = 2026.06.105-release~202606132048~ubuntu25.10.1
first_version = 2026.06.105-release~202606132048~ubuntu25.10.1
create_date = 2026-07-15 11:08
modify_date = 2026-07-15 11:09
directory = /home/egor-debian/Debian OPL/DEBIAN OPL 1.0

[Original]
iso_file_name = debian-opl-live-1.0--amd64.iso
iso_directory = /home/egor-debian/Debian OPL
iso_volume_id = Debian OPL
iso_release_name = Trixie-OPL
iso_disk_name = Debian OPL "Trixie-OPL"

[Custom]
iso_version_number = 
iso_file_name = debian-opl-live-1.0--amd64.iso
iso_directory = /home/egor-debian/Debian OPL/DEBIAN OPL 1.0
iso_volume_id = Debian OPL
iso_release_name = Trixie-OPL
iso_disk_name = Debian OPL "Trixie-OPL"

[Layout]
casper_directory = install, live
squashfs_directory = live
squashfs_file_name = filesystem.squashfs
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = 
size_file_name = filesystem.size
minimal_squashfs_file_name = 
minimal_manifest_file_name = 
minimal_size_file_name = 
standard_squashfs_file_name = 
standard_manifest_file_name = 
standard_size_file_name = 
installer_sources_file_name = 
installer_squashfs_file_name = 
installer_manifest_file_name = 
installer_size_file_name = 
installer_generic_squashfs_file_name = 
installer_generic_manifest_file_name = 
installer_generic_size_file_name = 

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C7D51CB8EC3200CBCE72BB8E5B26ED25754E5437A45404C6A2D810848D5B4EABF2F64D3554E7B41C30C1E8F315C59F9BA3B330DC8A97B97055070B7597AEA60909E01908DE8EFC2B4C62961B80E6D1D607F0EED13BDE3E9CD18BF16D87F801887B67C49E722A741F4C83BF2A8A2F3F3BB1A858F14C959D8EF68E853BF3F86ABD97061A8B7CC69BD15D2356064FB664BDEBA5CC00EC7CB960DA892C28E8702727ED0CE2B849C45488305A46C20D324DF10E889EC509F2ECBC879109E6D789C4764F5A3AE0B50ACAC9266C84E8F2A7BEC948829B2DCF21FB0936493661DE03099A565B19C609CE87EDB9D5686AC76B02642937E86A20361E25A85C93FA3AAF793AC50D3FA55FF7A37CDB9D96E2FAD03A4089D885B36CF7FD3613453287E00BACDB328
iso_checksum = 
iso_checksum_file_name = 

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = boot/grub/grub.cfg, boot/grub/install.cfg, boot/grub/install_start.cfg, isolinux/install.cfg, isolinux/live.cfg
compression = xz

